### ISSUE TITLE
Looks great

### ISSUE THREAD

**Issue by telegrambotdev** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#1]
Your work is awsome. but need some improvements.

can you add atleast a good theme and css to look  good. 

Thanks in advance

**Comment by developeranaz** [comment]
These index are assigned by rclone using serve command maybe i can't edit this.
but I will try to add good theme to improve this.

If i try to make the whole application in a different way the theme may be worse than this eg: url to mega of mine🤪

thanks @telegrambotdev

**Comment by telegrambotdev** [comment]
Thank you
