### ISSUE TITLE
Getting buildpack error!

### ISSUE THREAD

**Issue by Ghazni1337** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#2]
-----> Building on the Heroku-20 stack
-----> Determining which buildpack to use for this app
 !     No default language could be detected for this app.
			HINT: This occurs when Heroku cannot detect the buildpack to use for this application automatically.
			See https://devcenter.heroku.com/articles/buildpacks
 !     Push failed

How can I solve this?

**Comment by developeranaz** [comment]
i think you had edited app.json file
1. delete your repo and fork again. 
2. copy rclone.conf in root of the repository
3. Then click here https://dashboard.heroku.com/new?template=https://github.com/Ghazni1337/HEROKU-RCLONE-SERVE-INDEX
.If any further issues comment here 🤗

**Comment by developeranaz** [comment]
Now i had re-edited the Entire repository.
* No fork needed
* Click on my rapid deployment button.
* Just paste your CLOUDNAME and CONFIG_IN_URL fields and deploy.
* See readme for more details

**Comment by Ghazni1337** [comment]
I want to host this script on my own Linux VPS (CentOs 7). Is it possible?

**Comment by developeranaz** [comment]
The script in this repo is a dockerfile only for Heroku

**Comment by Ghazni1337** [comment]
Can you create a script like this for VPS?

**Comment by developeranaz** [comment]
> Can you create a script like this for VPS?
How could i ignore you 😕
You should ask this to Some good developer i'mm not perfect.

**Comment by Ghazni1337** [comment]
Please try. I hope you can do it.

**Comment by developeranaz** [comment]
> Please try. I hope you can do it.

please provide all your
* VPS  details .
* How to serve - locally /public

I don't know i could complete this or not.

**Comment by Ghazni1337** [comment]
Linux - CentOS 7
Ram: 4 GB
Storage: SSD (80 GB)
Bandwidth: Unlimited
Want to serve files publicly.

**Comment by developeranaz** [comment]
> Linux - CentOS 7
> Ram: 4 GB
> Storage: SSD (80 GB)
> Bandwidth: Unlimited
> Want to serve files publicly.

is any domain available with this VPS

**Comment by Ghazni1337** [comment]
Yes. Domain Connected. Provider: Hetzner

**Comment by developeranaz** [comment]
> Yes. Domain Connected. Provider: Hetzner

You are wasting your time.

I don't have a paid cloud hosting service. Thats why i'mm using heroku

**Comment by developeranaz** [comment]
> Yes. Domain Connected. Provider: Hetzner

Hello @Ghazni1337 , it's been a long time.
I tried to write you a script, Unfortunately I couldn't do that.
This has to be done manually so I can't do a bash scripting.

**Comment by developeranaz** [comment]
If you still have any problems, you can contact me personally 
Telegram : https://t.me/gitdeveloperanaz
