### ISSUE TITLE
need auth option

### ISSUE THREAD

**Issue by telegrambotdev** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#6]
can you add an option for auth as a config far like uesername:password, it should be an optional config

auth = test : test

**Comment by developeranaz** [comment]
it is not possible because google drive and some other Cloud services  doesn't allow this user and password directly.


But mega would allow that option thats why i had made Mega.nz-Rclone-index-HEROKU

**Comment by telegrambotdev** [comment]
what abput http bsic auth,isnt that possible ?

**Comment by telegrambotdev** [comment]
> it is not possible because google drive and some other Cloud services doesn't allow this user and password directly.
> 
> But mega would allow that option thats why i had made Mega.nz-Rclone-index-HEROKU

i saw some gdrive index providers supports auth function

eg https://github.com/ParveenBhadooOfficial/Google-Drive-Index

**Comment by developeranaz** [comment]
Ok, Now i get it
Here, OAuth process is done by rclone and rclone encrypt your secret.
I can Add it in deployment section But this is a common index, this repo can index all rclone supported cloud. ie., Ondrive, Mega ,googledrive, googlephotos, BOX etc...

I can make it in another repository only for google drive seperately. unfortunately i'mm already working on some other projects. So i don't have time to make a new one.
please kindly understand my situation.

I will make that repository and publish it soon.

**Comment by telegrambotdev** [comment]
I got it.kindly tag me when you make one
