### ISSUE TITLE
Is it possible to deploy it on Cloudflare Workers?

### ISSUE THREAD

**Issue by neelygenet** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#7]
First of all, congratulations for this wonderful work!
I was thinking about to deploy it on Cloudflare Workers, but I am not sure if it is possible.
I am wanting it because Heroku has 2TB bandwidth limit per month, which is not sufficient for me :-(

**Comment by developeranaz** [comment]
Sorry @neelygenet 
We can't install this application to serverless Cloudflare Workers. You can Make multiple heroku account by using yandex.mail  to fix that issue.
Maybe in future some others developers would do that work.

**Comment by developeranaz** [comment]
Thanks for your comment here, feel free to post any issues and your thoughts. Thanks for your wonderful support. I will keep building this type of project and try to improve my repository better than this.🤗

**Comment by neelygenet** [comment]
@developeranaz I appreciate your efforts to create it and I hope I can contribute with you soon!! Thank you very much.
If you have a Telegram account, I would love to keep a closer contact with you 😄

**Comment by developeranaz** [comment]
thats great 
my TG link https://t.me/gitdeveloperanaz
