### ISSUE TITLE
is there a method to edit the index.html ?

### ISSUE THREAD

**Issue by jakiya99** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#8]
great work buddy ! 
is there a method to edit the index.html? 
rclone tokens are tempory  or valid for long time?

**Comment by developeranaz** [comment]
The validity of the token depends on the type of cloud/remote control you are using.
I think google drive lasts a long time I don't know the exact time
Currently i'mm building a new index for this repository. I don't know how it wíll react to rclone.
Maybe a  Weird index like 'Aria2rclone remote uploader' in my repo 🤗

**Comment by jakiya99** [comment]
ok waiting for new update
