### ISSUE TITLE
Is this really unlimited?

### ISSUE THREAD

**Issue by sunilroy007** [developeranaz/HEROKU-RCLONE-SERVE-INDEX#9]
I just read in readme it says UNLIMITED download  and no quota issues. Is it true anyone tested it?

**Comment by developeranaz** [comment]
> I just read in readme it says UNLIMITED download and no quota issues. Is it true anyone tested it?

It may be unlimited no one tested that. Somewhere i heard 750gb/day for google drive (not sure) , but google never mentioned any limit for backends.

NOTE: heroku only have 2TB bandwidth for free dyno per month.

**Comment by sunilroy007** [comment]
Hmm.. no quota limit is missleading then in readme

**Comment by developeranaz** [comment]
> Hmm.. no quota limit is missleading then in readme

This repository is not only for googledrive but is capable of many other drives, moreover in the case of googledrive Google has never said any quota limit. So, what can I do.
